version: "3.3"

services:
  app:
    image: nemo:1.0.0
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./models:/app/models
      - ./.env:/app/.env
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - DEEPFACE_HOME=/app/models
    shm_size: '8gb'
