version: "3.7"

services:
  app:
    image: keelezibel/diarization-pyannote:1.0.0
    volumes:
      - ./models:/models
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./src:/app/src
      - .env:/app/.env
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - DEEPFACE_HOME=/app/models
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    shm_size: '8gb'
